/* -----------------
 * ServletOutputImage.java
 * -----------------
 * (C) Copyright 2002-2004, by Object Refinery Limited.
 *
 */

package ibd.fundCheckCharts;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Vector;
import javax.servlet.RequestDispatcher;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * A basic servlet that generates an HTML page that displays a chart generated by
 * JFreeChart.
 * <P>
 * This servlet uses another servlet (ServletDemo2ChartGenerator) to create a PNG image
 * for the embedded chart.
 * <P>
 * This class is described in the JFreeChart Developer Guide.
 */
public class ServletOutputImage extends HttpServlet {

    /**
     * Creates a new servlet demo.
     */
    public ServletOutputImage() {
        // nothing required
    }

    /**
     * Processes a POST request.
     * <P>
     * The chart.html page contains a form for generating the first request, after that
     * the HTML returned by this servlet contains the same form for generating subsequent
     * requests.
     *
     * @param request  the request.
     * @param response  the response.
     * @throws ServletException if there is a servlet related problem.
     * @throws IOException if there is an I/O problem.
     */
    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

        PrintWriter out = new PrintWriter(response.getWriter());
        try {

	    String fund = request.getParameter("fund");

	    out.println("<IMG ALT=\"Can't find fund "+fund+"\" SRC=\"ServletFundChartGenerator?time=5&fund="+fund+"\" BORDER=1 WIDTH=200 HEIGHT=200/>");
	    out.println("<IMG ALT=\" \" SRC=\"ServletFundChartGenerator?time=10&fund="+fund+"\" BORDER=1 WIDTH=200 HEIGHT=200/>");
	    out.println("<IMG ALT=\" \" SRC=\"ServletFundChartGenerator?time=15&fund="+fund+"\" BORDER=1 WIDTH=200 HEIGHT=200/>");

	    out.flush();
            out.close();
        }
        catch (Exception e) {
            System.err.println(e.toString());
        }
        finally {
            out.close();
        }
    }
}

