/* -------------------------------
 * ServletChartGenerator.java
 * -------------------------------
 * (C) Copyright 2002-2004, by Object Refinery Limited.
 *
 */
package ibd.fundCheckCharts;

import java.io.IOException;
import java.io.OutputStream;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.RequestDispatcher;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;

/**
 * A servlet that returns one of three charts as a PNG image file.  This servlet is
 * referenced in the HTML generated by ServletDemo2.
 * <P>
 * Three different charts can be generated, controlled by the 'type' parameter.  The possible
 * values are 'pie', 'bar' and 'time' (for time series).
 * <P>
 * This class is described in the JFreeChart Developer Guide.
 */
public class ServletFundChartGenerator extends HttpServlet {
    private String fund;

//    public static JFreeChart chart5=null;
//    public static JFreeChart chart10=null;
    /**
     * Default constructor.
     */
    public ServletFundChartGenerator() {
	// nothing required
    }

    /**
     * Process a GET request.
     *
     * @param request  the request.
     * @param response  the response.
     * @throws ServletException if there is a servlet related problem.
     * @throws IOException if there is an I/O problem.
     */
    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response)
	    throws ServletException, IOException {

	String timeString = request.getParameter("time");
	int time = Integer.valueOf(timeString);
	fund = request.getParameter("fund");
	System.out.println("HERE IS THE FUND! "+fund);
	Vector gains = GetFundData.getData(fund);
	System.out.println("HERE ARE THE GAINS!!!!!!!!!!!!!!!!");
	System.out.println(gains);

	JFreeChart chart = null;

	OutputStream out = response.getOutputStream();
	try {
	    chart = ReturnFundChart.returnChart(time, gains, fund);

	    if (chart != null) {
		response.setContentType("image/png");
		ChartUtilities.writeChartAsPNG(out, chart, 400, 300);
		out.flush();
		out.close();
	    } 
	    
	} catch (Exception ex) {
	    System.err.println(ex.toString());
	    Logger.getLogger(GetFundData.class.getName()).log(Level.SEVERE, null, ex);
	    request.setAttribute("error",ex);
	    request.setAttribute("fund",fund);
	    RequestDispatcher rd = request.getRequestDispatcher("/fundDataError.jsp");
	    rd.forward(request, response);
	} finally {
	    out.close();
	}
    }
}
